name: continuous-integration
on: [pull_request]
jobs:

    - name: Install JavaScript dependencies with Yarn
      run: |
        yarn check || yarn install;

  unit-tests:
    runs-on: ubuntu-latest
    needs: setup-test-environment
    steps:
    - name: "Unit Tests"
      env:
        RAILS_ENV: test
        DB_PASSWORD: root
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: bundle exec rails test test/unit

  functional-tests:
    runs-on: ubuntu-latest
    needs: setup-test-environment
    steps:
    - name: "Functional Tests"
      env:
        RAILS_ENV: test
        DB_PASSWORD: root
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: bundle exec rails test test/functional

  integration-tests:
    runs-on: ubuntu-latest
    needs: setup-test-environment
    steps:
    - name: "Integration Tests"
      env:
        RAILS_ENV: test
        DB_PASSWORD: root
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: bundle exec rails test test/integration

  system-tests:
    runs-on: ubuntu-latest
    needs: setup-test-environment
    steps:
    - name: "System Tests"
      env:
        RAILS_ENV: test
        DB_PASSWORD: root
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        bundle exec rails test:system
