image:
  file: .gitpod.dockerfile
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      bundle install --without production &&
      cp config/database.yml.example config/database.yml &&
      cp db/schema.rb.example db/schema.rb &&
      bundle config set path 'vendor/.bundle/' &&
      bundle install &&
      mysql -e "CREATE DATABASE plots;"; &&
      bundle exec rake db:schema:load &&
      bundle exec rails db:migrate
    command: >
      rails server
github:
    prebuilds:
        pullRequestsFromForks: true
